version: '3.8'

services:
  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node app.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - db
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./mysql2:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
